### ISSUE TITLE
shorthand for response mime types

### ISSUE THREAD

**Issue by benatkin** [jdegoes/blueeyes#11]
Looking at the example in the README I thought that most of it looked like the problem domain, a web DSL, and Scala syntax. It's pretty terse. One thing that jumped out at me as possibly taking more of the room than is necessary was `application/json`. I think if somehow it just said just `json` that would be more ideal. I'm not sure if this differs conceptually from how OK is used instead of 200 OK.

**Comment by jdegoes** [comment]
'application/json' is the exact mime-type you would use if you wanted to manually set the Content-Type header. Rather than invent our own nicknames for common data types, we chose to adhere to HTTP standards and terminology whenever possible, following our philosophy of "embracing the language and machinery of HTTP". This gives you the benefit that if you want to know what content type to use, you can just Google standard mime types, and translate directly into Scala (no need to cross reference mime types with internal "nicknames" for them).
